# This file should only be used as reference;
# please modify it to suit your server's needs.
version: "3"
services:
  spigot:
    build: .
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      SPIGOT_JAVA_FLAGS: "-Xmx2048M" # beef up the server to 2GB of RAM
    volumes:
      - "./server:/spigot" # store server files in ./server
