version: "3"
services:
  spigot:
    image: academusapp/spigot:latest
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      SPIGOT_JAVA_FLAGS: "-Xmx2048M" # beef up the server to 2GB of RAM
    volumes:
      - "./server:/spigot" # store server files in ./server
